import random

short_responses = [

    "Yep, I'm here.",
    "Yeah? What's up?",
    "Hey, what's going on?",
    "What's up?",
    "Hey, I'm listening.",
    "Go ahead.",
    "I'm listening.",
    "Sure, what's up?",
    "Yeah, tell me.",
    "I'm right here.",
    "What's on your mind?",
    "What do you need?",
    "How can I help?",
    "What can I do for you?",
    "I'm all ears.",
    "Go for it.",
    "I'm with you.",
    "Tell me.",
    "Sure, go ahead.",
    "Yeah, I'm here.",

    "Hey! How can I help?",
    "Hey there!",
    "Good to hear from you.",
    "Nice to hear from you.",
    "Of course, I'm here to help.",
    "Absolutely, what do you need?",
    "Sure thing.",
    "Of course.",
    "You got it.",
    "I've got you.",
    "Happy to help.",
    "Always happy to help.",
    "No problem.",
    "I'm on it.",
    "I can help with that.",
    "Sounds good.",
    "Sure, let's do it.",
    "Absolutely.",
    "Anytime.",
    "You know I'm here.",

    "Yeah, what's up?",
    "What's happening?",
    "What are we doing?",
    "What are you thinking?",
    "So, what's the plan?",
    "What's the move?",
    "What are we working on?",
    "Alright, I'm listening.",
    "Alright, what's up?",
    "Okay, I'm listening.",
    "Okay, tell me.",
    "I'm ready whenever you are.",
    "Take it away.",
    "Let's hear it.",
    "I'm listening, go ahead.",
    "Alright, let's do this.",
    "Sure, I'm with you.",
    "Yeah, I've got you.",
    "I'm here. What's up?",
    "Alright, what do you need?",

    "You called?",
    "I'm here. What happened?",
    "What's cooking?",
    "Alright, hit me.",
    "Okay, I'm curious.",
    "Now you've got my attention.",
    "Alright, I'm all ears.",
    "Okay, let's hear it.",
    "I'm listening. What's the story?",
    "Alright, what have you got?",
    "Well, I'm listening.",
    "You've got my attention.",
    "Alright, what's on your mind?",
    "I'm curious. What's up?",
    "Okay, what's going on?",

    "Right here. What can I do?",
    "I'm online. What's up?",
    "I'm here and ready to help.",
    "Everything's ready. What do you need?",
    "I'm ready. What's the plan?",
    "I'm here whenever you need me.",
    "Ready when you are.",
    "I'm good to go.",
    "I'm ready. Just say the word.",
    "I'm here. Just let me know.",
    "All set. What can I do?",
    "I'm ready whenever you need me.",
    "Everything's good on my end.",
    "I'm here and listening.",
    "Alright, I'm ready. What's up?"
]

def get_random_response():
    return random.choice(short_responses)